# Introduction to QuTiP

[Source](https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/lectures/Lecture-0-Introduction-to-QuTiP.ipynb)

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

# QuTiP imports

from qutip import (Qobj, about, basis, coherent_dm, create, destroy, displace,coherent, expect,
                   fock, fock_dm,mesolve,qeye, sigmax, sigmay, sigmaz, tensor, thermal_dm)

## What is QuTiP?

It is a Python Package for calculations and numerical simulations of quantum systems. It includes facilities for representing and doing calculations with quantum objects such as state vectors, quantum operators of single and composite systems, and superoperators.

It also includes solvers for a time-evolution of quantum systems, according to: 
1. Schrodinger Equation
2. von Neuman Equation
3. Master Equations
4. Floquet formalism
5. Monte Carlo quantum trajectories
6. experimental implementations of stochastic master equations.

### Installation

```python
pip install qutip
```

## Quantum Object Class: `qobj`

Most basic building blovk of QuTiP package is the `Qobj` class, which is used for representing quantum objects such as states and operators. The `Qobj` class contains all the information required to describe a quantum system, such as its matrix representation, composite strcutures and dimensionality

### Creating and Inspecting Quantum Objects

We can create a new quantum object using the `Qobj` class constructor, like this

In [3]:
q = Qobj([[1], [0]])
q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

We passed a python list as an argument to the class constructor. The data in the list is used to construct the matrix representation of the quantum objects, and the other properties of the quantum object is by default computed from the same data. 

We can inspect the properties of a `Qobj` instance using the following

In [4]:
q.dims # the dimensions of the quantum object

[[2], [1]]

In [5]:
q.shape # the shape of the quantum object

(2, 1)

In [6]:
q.data # the data of the quantum object

<2x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [7]:
q.full() # the full dense matrix representation of the quantum object

array([[1.+0.j],
       [0.+0.j]])

In [9]:
q.isherm # check if the quantum object is Hermitian


False

In [10]:
q.type # check the type of the quantum object

'ket'

### Using `Qobj` insances for calculations

Wih `Qobj` instances we can do arithmetic and apply a number of different operations using class methods:

In [11]:
sy = Qobj([[0, -1j], [1j,0]]) # the sigma-y Pauli operator
sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [12]:
sz = Qobj([[1, 0], [0, -1]]) # the sigma-z Pauli operator
sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [15]:
# let's do some arithectic with quantum objects

H = 1.0 * sz + 0.1 *sy
print("Qubit Hamiltonian = \n")
H

Qubit Hamiltonian = 



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

Modifying quantum objects using the `Qobj` methods

In [16]:
sy.dag() # the Hermitian conjugate of the sigma-y operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [17]:
H.tr() # the trace of the Hamiltonian

0.0

In [19]:
H.eigenenergies() # the eigenenergies of the Hamiltonian

array([-1.00498756,  1.00498756])

To get a complete list of methods and properites, either visit the [official site](https://qutip.org/docs/latest/index.html) or do this:

In [20]:
help(Qobj)

Help on class Qobj in module qutip.qobj:

class Qobj(builtins.object)
 |  Qobj(inpt=None, dims=None, shape=None, type=None, isherm=None, copy=True, fast=False, superrep=None, isunitary=None)
 |  
 |  A class for representing quantum objects, such as quantum operators
 |  and states.
 |  
 |  The Qobj class is the QuTiP representation of quantum operators and state
 |  vectors. This class also implements math operations +,-,* between Qobj
 |  instances (and / by a C-number), as well as a collection of common
 |  operator/state operations.  The Qobj constructor optionally takes a
 |  dimension ``list`` and/or shape ``list`` as arguments.
 |  
 |  Parameters
 |  ----------
 |  inpt : array_like
 |      Data for vector/matrix representation of the quantum object.
 |  dims : list
 |      Dimensions of object used for tensor products.
 |  shape : list
 |      Shape of underlying data structure (matrix shape).
 |  copy : bool
 |      Flag specifying whether Qobj should get a copy of the
 |   

In [21]:
dir(Qobj)

['__abs__',
 '__add__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pow__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_repr_latex_',
 'check_herm',
 'check_isunitary',
 'conj',
 'copy',
 'cosm',
 'dag',
 'data',
 'diag',
 'dnorm',
 'dual_chan',
 'eigenenergies',
 'eigenstates',
 'eliminate_states',
 'evaluate',
 'expm',
 'extract_states',
 'full',
 'get_data',
 'groundstate',
 'inv',
 'isbra',
 'iscp',
 'iscptp',
 'isherm',
 'ishp',
 'isket',
 'isoper',
 'isoperbra',
 'isoperket',
 

## States and Operators